spring:
  application:
    name: spring-boot-demo
  datasource:
    url: jdbc:mysql://121.161.22.225:3306/wichan
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wichan
    password: wichan
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  port: 8080

mybatis:
  mapper-locations: "classpath:mapper/**.xml"
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://demouser:demopassword@localhost:8761/eureka

logging:
  level:
    root: debug
