# default
server:
  port: 8080

spring:
  application:
    name: spring-boot-demo
  elasticsearch:
    uris: http://121.161.22.225:9200
  datasource:
    url: jdbc:mysql://121.161.22.225:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: demo
  web:
    resources:
      # ResourceHttpRequestHandler 매핑 여부
      add-mappings: false
  mvc:
    # handler 미매핑 시 throw error 여부
    throw-exception-if-no-handler-found: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 30000 # default 60,000ms
            read-timeout: 10000 # default 10,000ms

# mybatis
mybatis:
  mapper-locations: "classpath:mapper/**.xml"
  configuration:
    map-underscore-to-camel-case: true

# spring actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true

logging:
  level:
    root: info
  config: "classpath:logger/logback.xml"

external-servers:
  comment-client:
    endpoint: "https://jsonplaceholder.typicode.com/comments"
  post-client:
    endpoint: "https://jsonplaceholder.typicode.com/posts"

---
# 개발기 override 설정 추가
spring:
  config:
    activate:
      on-profile: dev
# ..todo

---
# 운영기 override 설정 추가
spring:
  config:
    activate:
      on-profile: prod
# ..todo