# default
server:
  port: 8080

spring:
  application:
    name: spring-boot-demo
  datasource:
    url: jdbc:mysql://121.161.22.225:3306/wichan
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wichan
    password: wichan
  web:
    resources:
      # ResourceHttpRequestHandler 매핑 여부
      add-mappings: false
  mvc:
    # handler 미매핑 시 throw error 여부
    throw-exception-if-no-handler-found: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://demouser:demopassword@121.161.22.225:5601/eureka

mybatis:
  mapper-locations: "classpath:mapper/**.xml"
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: debug

---
# 개발기 override 설정 추가
spring:
  config:
    activate:
      on-profile: dev

---
# 운영기 override 설정 추가
spring:
  config:
    activate:
      on-profile: prod
