-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1ZKsaU6eIpMGhGQP
NNzeEAhxkma47cNuhKEYLpWO7j2gCgYIKoZIzj0DAQehRANCAAQcIEDrQdM4tLnD
zpDN8g5pZ7ksVoiyFmG3yj6SqRIfXI5Zrz6sLoIWUoFrgIKBl9x+v0qoJ5O3fOgZ
uksR5GFa
-----END PRIVATE KEY-----